name: Build QMK Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build firmware
        run: qmk compile -kb totem -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: totem_vial_firmware
          path: |
            *.uf2
            *.hex
